modLoader = "javafml"
loaderVersion = "[45,)"
license = "Code: LGPLv3 \nAssets: All Rights Reserved"
issueTrackerURL = "https://github.com/AOCAWOL/BYG/issues"
[[mods]]
modId = "byg"
version="${file.jarVersion}"
displayName = "Oh The Biomes You'll Go"
displayURL = "https://oh-the-biomes-youll-go.fandom.com/wiki/Oh_The_Biomes_You%27ll_Go_Wiki"
logoFile = "logo_text.png"
credits = "Some Artwork: CupOfJoe, SaltySeaDoggo, Spare, Paul; Some Code: TelepathicGrunt, Paul, HauntedPasta, TheModdingInquisition"
authors = "AOCAWOL, Corgi Taco, YaBoiChips, JT122406"
description = '''
An Adventure and Exploration mod with over 80 new biomes!

Notice: The linked wiki is not owned by BYG, the wiki is open for anyone to edit and any inaccuracies that may appear are not BYG's responsibility.
'''
[[dependencies.byg]]
modId = "forge"
mandatory = true
versionRange = "[45.1.00,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "terrablender"
mandatory = true
versionRange = "[2.2.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "corgilib"
mandatory = true
versionRange = "[3.0.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.byg]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.byg]]
modId = "soulfired"
mandatory = false
versionRange = "[3.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "sereneseasons"
mandatory = false
versionRange = "[8.3.0.40,)"
ordering = "NONE"
side = "BOTH"