modLoader = "javafml"
loaderVersion = "[33,)"
license = "Code: LGPLv3 \nAssets: All Rights Reserved"
issueTrackerURL = "https://github.com/CorgiTaco/BYG/issues"
[[mods]]
modId = "byg"
version = "1.1.5"
displayName = "Oh The Biomes You'll Go"
displayURL = "https://bygmc.weebly.com/"
logoFile = "logo_text.png"
credits = "On curse"
authors = "AOCAWOL & Corgi Taco"
description = '''
An Adventure and Exploration mod with over 60 new biomes!
'''
[[dependencies.byg]]
modId = "forge"
mandatory = true
versionRange = "[34.1.42,)"
ordering = "NONE"
side = "BOTH"