name: 1.19 Bug Report
description: Report any bugs here! Report crashes using "Crash Report"
title: "[1.19][Bug]: "
labels: [ "Bug", "1.19" ]
body:
  - type: markdown
    attributes:
      value: |
        **Prior to filling out this bug report please try the following:**
        * Reset your configs! Configurations typically change between mod updates and are typically the most common causes of crashes. To reset your configs, move your existing configs to a separate directory that isn't your MC installation directory, run the game, and update the values from your old config in the newly generated config!
        Here's how to delete your BYG configs: 
        ![Resetting configs](https://user-images.githubusercontent.com/66983020/236601583-9cdc2625-13ee-4deb-8b99-17b510f1b3aa.gif)
        *[If you're using a launcher such as CurseForge, MultiMC, GDLauncher, Prism Launcher or any other launcher, please click here](https://github.com/AOCAWOL/BYG/wiki/Resetting-Configs)*
        
        * Isolate this mod on its own and attempt to reproduce the crash with the mod. If it works on its own, this is more than likely a mod incompatibility. Please make sure to mention whether or not this is a mod incompatibility in the "What Happened" section of this issue!
        
        * **TITLE THIS ISSUE PROPERLY**
  - type: input
    id: mod-version
    attributes:
      label: BYG Version
      description: |
        What version of the mod are you using? Make sure you are using the latest version available!
        Latest version downloads can be found here: 
        Forge: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files
        Fabric: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files
        Other Mod loaders: N/A
      placeholder: ex. 1.2.1
    validations:
      required: true
  - type: input
    id: terrablender-version
    attributes:
      label: Terrablender Version
      description: |
        What version of Terrablender are you using? 
        Terrablender is a required mod for BYG in 1.18+, if you're using 1.16, specify N/A.
        Latest version downloads can be found here: 
        Forge: https://www.curseforge.com/minecraft/mc-mods/terrablender/files
        Fabric: https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric/files
        Other Mod loaders: N/A
      placeholder: ex. 1.1.0.99
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: What Mod Loader are you running? Mod loaders not listed are not supported.
      options:
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      description: What version of the mod loader are you using?
      placeholder: ex. 36.0.45
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Severity
      description: Would you describe the bug as minor or major? Something minor would be a missing loot table. An example of something major would be a mod incompatibility. Just use good judgement when specifying the severity and the impact on gameplay.
      options:
        - Major
        - Minor
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please give a thorough explanation of the issue(s) you found. Attach/Link relevant images/files in relation to the issue(s)!
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: latest-log
    attributes:
      label: latest.log
      description: Please upload your latest.log file directly here or use https://gist.github.com/ and leave the link here.
      placeholder: Drag and drop latest.log file here or link it with https://gist.github.com/!
    validations:
      required: true
  - type: dropdown
    id: isolate-mod
    attributes:
      label: Did you isolate BYG?
      description: |
        Did you try a separate instance with BYG only and its required dependencies and manage to recreate the issue?? **If not please do so now!**
      options:
        - I tried BYG alone
        - I did not try BYG alone
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Agreement
        Before submitting this issue, you must agree to and try the following: 
        * **If this is a crash, please use the crash report form!**
        * I am not asking a question.
            * Is this a question? Please feel free to join our [Discord](https://discord.gg/zQA4eez2eS) or asking in our [Discussions Tab](https://github.com/AOCAWOL/BYG/discussions/)!
        * I am not making a feature request.
            * Is this a feature request? Please post it in our [Discussions Tab](https://github.com/AOCAWOL/BYG/discussions/)!
        * I am using the right version of Minecraft & correct mod loader for my version of BYG.
            * BYG jars have their MC version and mod loader listed in the file name.
                * Ie: `Oh_The_Biomes_You'll_Go-**fabric**-**1.19.2**-2.0.1.0.jar` or `Oh_The_Biomes_You'll_Go-**forge**-**1.19.2**-2.0.1.0.jar`
        * I am using the correct version of Java. 1.19 uses Java 17, and I should not be using any other higher or lower version.
        * I am using the latest version of BYG as listed [here](https://github.com/AOCAWOL/BYG#official-downloads) for my MC version.
        * I am using the required dependencies for BYG for my MC version as listed [here](https://github.com/AOCAWOL/BYG#dependencies).
        * **I am using the Fabric or Forge Mod Loader** and I understand BYG has no interest in supporting other mod loaders at this time. *PRs for other mod loader related fixes are welcomed but this issue tracker will not track issues related to other mod loaders*.
            * I understand issue reports for other mod loaders will be immediately closed and locked.
        * If this is a game crash...
            * I have reset/deleted BYG configs by following the guide provided [here](https://github.com/AOCAWOL/BYG/wiki/Resetting-Configs) and relaunched my game with BYG and my issue still persists.
        * I have isolated BYG alongside its required dependencies and tested whether this issue exists with BYG & its dependencies or other 3rd party mods.
            * If this issue doesn't exist with BYG and its dependencies alone but with a 3rd party mod, I have specified that this issue only occurs with another mod and have listed the problematic mod with a link to it in the "What Happened?" segment of this issue report.
            * I have also reported this issue to the conflicting mod to inform the other mod authors.
        * I have properly titled this issue clearly outlining the issue so others do not create duplicate issues.
        * I have checked both open and closed issues on the [BYG GitHub Issue Tracker](https://github.com/AOCAWOL/BYG/issues) before reporting my issue.
        * I have provided videos/pictures related to the issue. 
        * If I'm using a modpack, the modpack developers have been notified of this issue.
        * I have provided both my `latest.log` and crash log (if applicable) files. 
            * Believe it or not, your latest.log may provide valuable information so **we really recommend providing it whether you think it helps or not.**
        * I understand that if my issue is marked with the label "Requires Information" after my issue is reviewed and no other comments are made on my issue, the issue will be closed after 30 days.
            * We suggest [turning on your GitHub notifications](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications) to stay up to date with this issue!
        * I understand that this issue may remain open for a prolonged period of time with no activity and that the developers have lives outside of modding Minecraft.
  - type: checkboxes
    id: agreement
    attributes:
      label: Did you read and understand the above agreement?
      description: |
        Did you read and understand the above agreement? **You will not be able to submit this issue unless you agree to the agreement.**
      options:
        - label: I agree.
    validations:
      required: true